# TCL File Generated by Component Editor 18.1
# Fri Sep 30 09:15:58 EDT 2022
# DO NOT MODIFY


# 
# my_custom_ip "my_custom_ip" v1.0
# Anton Bogovik 2022.09.30.09:15:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_custom_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME my_custom_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ESDI_IP
set_module_property AUTHOR "Anton Bogovik"
set_module_property DISPLAY_NAME my_custom_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL custom_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file custom_ip.vhd VHDL PATH Custom_Component_Support_Files/custom_ip.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0_1_1
# 
add_interface avalon_slave_0_1_1 avalon end
set_interface_property avalon_slave_0_1_1 addressUnits WORDS
set_interface_property avalon_slave_0_1_1 associatedClock clock
set_interface_property avalon_slave_0_1_1 associatedReset reset
set_interface_property avalon_slave_0_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1_1 holdTime 0
set_interface_property avalon_slave_0_1_1 linewrapBursts false
set_interface_property avalon_slave_0_1_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1_1 readLatency 0
set_interface_property avalon_slave_0_1_1 readWaitTime 1
set_interface_property avalon_slave_0_1_1 setupTime 0
set_interface_property avalon_slave_0_1_1 timingUnits Cycles
set_interface_property avalon_slave_0_1_1 writeWaitTime 0
set_interface_property avalon_slave_0_1_1 ENABLED true
set_interface_property avalon_slave_0_1_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1_1 write write Input 1
add_interface_port avalon_slave_0_1_1 address address Input 3
add_interface_port avalon_slave_0_1_1 writedata writedata Input 32
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_1_1
# 
add_interface conduit_end_1_1 conduit end
set_interface_property conduit_end_1_1 associatedClock clock
set_interface_property conduit_end_1_1 associatedReset reset
set_interface_property conduit_end_1_1 ENABLED true
set_interface_property conduit_end_1_1 EXPORT_OF ""
set_interface_property conduit_end_1_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1_1 ext_addr_export ext_addr Input 3
add_interface_port conduit_end_1_1 ext_data_export ext_data Output 32
add_interface_port conduit_end_1_1 invalid_export invalid Input 1


# 
# connection point interrupt_sender_1_1
# 
add_interface interrupt_sender_1_1 interrupt end
set_interface_property interrupt_sender_1_1 associatedAddressablePoint avalon_slave_0_1_1
set_interface_property interrupt_sender_1_1 associatedClock clock
set_interface_property interrupt_sender_1_1 associatedReset reset
set_interface_property interrupt_sender_1_1 bridgedReceiverOffset ""
set_interface_property interrupt_sender_1_1 bridgesToReceiver ""
set_interface_property interrupt_sender_1_1 ENABLED true
set_interface_property interrupt_sender_1_1 EXPORT_OF ""
set_interface_property interrupt_sender_1_1 PORT_NAME_MAP ""
set_interface_property interrupt_sender_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender_1_1 SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender_1_1 irq irq Output 1

